version: '2'

services:

  seleniumhub:
    image: selenium/hub
    ports:
      - "4444:4444"

  firefoxnode:
    image: selenium/node-firefox-debug
    ports:
      - 4577
      - "4591:5900"
    links:
      - seleniumhub:hub
    depends_on:
      - seleniumhub
    environment:
      HUB_HOST: seleniumhub
      

  chromenode:
    image: selenium/node-chrome-debug
    ports:
      - 4578
      - "4592:5900"
    links:
      - seleniumhub:hub  
    depends_on:
      - seleniumhub
    environment:
      HUB_HOST: seleniumhub

  firefoxnode2:
    image: selenium/node-firefox-debug
    ports:
      - 4579
      - "4593:5900"
    links:
      - seleniumhub:hub
    depends_on:
      - seleniumhub
    environment:
      HUB_HOST: seleniumhub
      

  chromenode2:
    image: selenium/node-chrome-debug
    ports:
      - 4580
      - "4594:5900"
    links:
      - seleniumhub:hub  
    depends_on:
      - seleniumhub
    environment:
      HUB_HOST: seleniumhub      
